In [7]:
import numpy as np
import scipy

new_track_array = np.array([])
dummy = True
for k in range (1,12):
        print new_track_array.shape
        new_position = np.array([[1],[2]])
        if dummy:
                new_track_array = new_position
                dummy = False
        else: 
                new_track_array = np.append(new_track_array,new_position,axis=1)
print new_track_array

(0,)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(2, 7)
(2, 8)
(2, 9)
(2, 10)
[[1 1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2 2]]


In [20]:
from numpy import linalg as LA
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[1],[1]])
#a = np.array([])
if a.size != 0:
    c = a-b
    d = LA.norm(c, axis=0)
    print c
#d = np.array([])
print d
if d.size != 0:
    e = np.amin(d)
    print e
print a[1,1]


[[0 1 2]
 [1 2 3]]
[ 1.          2.23606798  3.60555128]
1.0
3
